### ISSUE TITLE
USB-Keyboard not working

### ISSUE THREAD

**Issue by netaddict** [andigandhi/bitpixie#6]
Hi,

I got bixpixie running, it boots somewhat successful on the target device (Fujitsu Stylistic) via an attached USB to ethernet adapter. My problem is, that after booting, I see a lot of messages on the screen (even that my USB keyboard is detected) but it isn't working. Ethernet isn't working ether, so I can't ssh into the machine. I'm a bit out of clou right now. 🤔😅

**Comment by andigandhi** [comment]
Hey! Did you use the provided alpine-initrd.xz image or did you build it yourself? The pre-compiled version is quite outdated, I will replace it as soon as I get dislocker running :D
Until now you will have to manually build it yourself using the `build-initramfs.sh` script.

**Comment by andigandhi** [comment]
Quick update: I just pushed a prebuilt initramfs, maybe try it again :)

**Comment by netaddict** [comment]
I used the provided, made my own and finally I used the new one from the repository. Still no luck. I can see even unplugging and plugging it in, but can't use it. 😅

![Image](https://github.com/user-attachments/assets/a779b46c-4704-49f2-b958-2697a06034d8)

**Comment by andigandhi** [comment]
I just reproduced it and will take a look into a fix. Looks like some modules or drivers are missing.

**Comment by andigandhi** [comment]
In the mean time you might be able to connect via SSH from the attacker machine: `ssh root@10.13.37.101`

**Comment by netaddict** [comment]
I fixed it myself, need just to figure out how to provide the fix, my GIT skills are somewhat degraded. ;)

**Comment by code1997** [comment]
@andigandhi you already implemented the network and ssh we talked about in #3 ?

**Comment by andigandhi** [comment]
@code1997 Yeah, I implemented it yesterday :D

**Comment by andigandhi** [comment]
Merged #7
